### ISSUE TITLE
如题

### ISSUE THREAD

**Issue by duoshoumiao** [RSRH-Rs/Hoshino-plugin-webscreenshot#1]
[2023-04-16 17:42:44,368] 127.0.0.1:55053 GET /ws/ 1.1 101 - 1048
[2023-04-16 17:42:46,644 nonebot] INFO: Self: 2622348412, Message 1655060298 from 645364231@[群:278656766]: '网页截图https://www.baidu.com'
[2023-04-16 17:42:46,644 webscreenshot] INFO: Message 1655060298 triggered screenshot.
[2023-04-16 17:42:47,261 webscreenshot] ERROR: <class 'playwright._impl._api_types.Error'> occured when screenshot handling message 1655060298.
[2023-04-16 17:42:47,261 webscreenshot] ERROR: Executable doesn't exist at C:\Users\Administrator\AppData\Local\ms-playwright\chromium-1055\chrome-win\chrome.exe
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot-master - 副本\HoshinoBot-master\hoshino\msghandler.py", line 21, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Administrator\Desktop\HoshinoBot-master - 副本\HoshinoBot-master\hoshino\modules\Hoshino-plugin-webscreenshot\__init__.py", line 40, in screenshot
    result = await screen_shot(url, nowtime)
  File "C:\Users\Administrator\Desktop\HoshinoBot-master - 副本\HoshinoBot-master\hoshino\modules\Hoshino-plugin-webscreenshot\utils.py", line 32, in screen_shot
    browser = await p.chromium.launch()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\async_api\_generated.py", line 14412, in launch
    await self._impl_obj.launch(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_connection.py", line 461, in wrap_api_call
    return await cb()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\_impl\_connection.py", line 96, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Executable doesn't exist at C:\Users\Administrator\AppData\Local\ms-playwright\chromium-1055\chrome-win\chrome.exe
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝
[2023-04-16 17:42:47,277 nonebot] INFO: Message 1655060298 is ignored: Handled by Hoshino

**Comment by RSRH-Rs** [comment]
在cmd输入一下playwright install即可~

**Comment by duoshoumiao** [comment]
> 在cmd输入一下playwright install即可~

 好的

**Comment by duoshoumiao** [comment]
> 在cmd输入一下playwright install即可~

![image](https://user-images.githubusercontent.com/94856184/232658606-eeb76039-b542-403b-9875-83ced5962e1c.png)

**Comment by RSRH-Rs** [comment]
是只有主动截图有这个报错吗，有没有试过加上https呢？自动截图也有这个报错嘛？

**Comment by duoshoumiao** [comment]
> 是只有主动截图有这个报错吗，有没有试过加上https呢？自动截图也有这个报错嘛？

![image](https://user-images.githubusercontent.com/94856184/232661634-43c17d01-0872-4aea-8c85-b79a164df948.png)

**Comment by duoshoumiao** [comment]
> 是只有主动截图有这个报错吗，有没有试过加上https呢？自动截图也有这个报错嘛？

![image](https://user-images.githubusercontent.com/94856184/232662426-c7ac0b1f-fcee-41ad-a778-75c37775863c.png)

**Comment by RSRH-Rs** [comment]
> > 是只有主动截图有这个报错吗，有没有试过加上https呢？自动截图也有这个报错嘛？
> 
> ![image](https://user-images.githubusercontent.com/94856184/232661634-43c17d01-0872-4aea-8c85-b79a164df948.png)
> 

好吧，我抽空修复一下~

**Comment by RSRH-Rs** [comment]
> > 是只有主动截图有这个报错吗，有没有试过加上https呢？自动截图也有这个报错嘛？
> 
> ![image](https://user-images.githubusercontent.com/94856184/232662426-c7ac0b1f-fcee-41ad-a778-75c37775863c.png)

好了，修好了~

**Comment by duoshoumiao** [comment]
> > > 是只有主动截图有这个报错吗，有没有试过加上https呢？自动截图也有这个报错嘛？
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/94856184/232662426-c7ac0b1f-fcee-41ad-a778-75c37775863c.png)
> 
> 好了，修好了~

我发现之前不加 网页截图4个字反而能发出来

**Comment by RSRH-Rs** [comment]
> > > > 是只有主动截图有这个报错吗，有没有试过加上https呢？自动截图也有这个报错嘛？
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/94856184/232662426-c7ac0b1f-fcee-41ad-a778-75c37775863c.png)
> > 
> > 好了，修好了~
> 
> 我发现之前不加 网页截图4个字反而能发出来

用新版吧新版更稳定，还有绿标检测开关~

**Comment by duoshoumiao** [comment]
> > > > > 是只有主动截图有这个报错吗，有没有试过加上https呢？自动截图也有这个报错嘛？
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/94856184/232662426-c7ac0b1f-fcee-41ad-a778-75c37775863c.png)
> > > 
> > > 
> > > 好了，修好了~
> > 
> > 
> > 我发现之前不加 网页截图4个字反而能发出来
> 
> 用新版吧新版更稳定，还有绿标检测开关~

感谢。目前https开头可以截图出来  网页截图+网站会超时  应该是我服务器的问题
